.mode columns
.header on
.nullvalue NULL
PRAGMA foreign_keys = ON;


.print ''
.print 'Estado incial das equipas com acesso as competicoes ou despromocao:'
.print ''
SELECT CLUBE.IDCOMPETICAODESPROMOCAO, COMPETICAODESPROMOCAO.NOME, CLUBE.NOME
FROM CLUBE JOIN COMPETICAODESPROMOCAO ON CLUBE.IDCOMPETICAODESPROMOCAO = COMPETICAODESPROMOCAO.IDCOMPETICAODESPROMOCAO;

.print ''
.print 'Insercao de dois jogos do Benfica com um golo em cada que faz com que este passe o Sporting na Classificacao'
.print 'e assim passe a ter acesso direto a Liga dos campeoes:'
.print ''
INSERT INTO JOGO (IDJOGO, JORNADA, DATA, IDESTADIO, IDCLUBEVISITANTE, IDCLUBEVISITADO) VALUES (500, 25, "2022-04-28", 3, 2, 3);
INSERT INTO JOGO (IDJOGO, JORNADA, DATA, IDESTADIO, IDCLUBEVISITANTE, IDCLUBEVISITADO) VALUES (501, 26, "2022-04-28", 3, 2, 3);

INSERT INTO GOLO (IDGOLO, MINUTO, IDJOGO, IDJOGADOR, IDCLUBE) VALUES (500, 28, 500, 115, 3);
INSERT INTO GOLO (IDGOLO, MINUTO, IDJOGO, IDJOGADOR, IDCLUBE) VALUES (501, 28, 501, 115, 3);

.print ''
.print 'Estado final das equipas com acesso as competicoes ou despromocao:'
.print 'VERIFICAR que a competicao do Benfica mudou de PLAYOFF LIGA DOS CAMPEOES para apenas LIGA DOS CAMPEOES'
.print 'VERIFICAR que a competicao do Sporting mudou de LIGA DOS CAMPEOES para apenas PLAYOFF LIGA DOS CAMPEOES'
.print ''
SELECT CLUBE.IDCOMPETICAODESPROMOCAO, COMPETICAODESPROMOCAO.NOME, CLUBE.NOME
FROM CLUBE JOIN COMPETICAODESPROMOCAO ON CLUBE.IDCOMPETICAODESPROMOCAO = COMPETICAODESPROMOCAO.IDCOMPETICAODESPROMOCAO;